# Generated by Django 5.1 on 2024-08-22 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('categoria', models.CharField(choices=[('MU', 'Manual de Usuario'), ('MT', 'Manual Técnico'), ('ET', 'Especificación Técnica'), ('DA', 'Documentación de API'), ('GI', 'Guía de Instalación'), ('IT', 'Informe Técnico'), ('DC', 'Documentación de Código'), ('EN', 'Ensayo'), ('TE', 'Tesis'), ('ARTC', 'Artículo Científico'), ('PI', 'Propuesta de Investigación'), ('IL', 'Informe de Laboratorio'), ('PRA', 'Publicación en Revista Académica'), ('CL', 'Contrato Legal'), ('TS', 'Testamento'), ('EP', 'Escritura de Propiedad'), ('AC', 'Acuerdo de Confidencialidad'), ('PPV', 'Políticas de Privacidad'), ('TC', 'Términos y Condiciones'), ('DJ', 'Demanda Judicial'), ('PA', 'Patente'), ('PN', 'Propuesta de Negocio'), ('PNB', 'Plan de Negocio'), ('IV', 'Informe de Ventas'), ('FA', 'Factura'), ('PR', 'Presupuesto'), ('ES', 'Estimación'), ('AM', 'Análisis de Mercado'), ('CC', 'Comunicación Corporativa'), ('NVL', 'Novela'), ('CT', 'Cuento'), ('PS', 'Poesía'), ('EL', 'Ensayo Literario'), ('GU', 'Guión'), ('CR', 'Crónica'), ('BI', 'Biografía'), ('CV', 'Currículum Vitae'), ('CPZ', 'Carta de Presentación')], max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
