# Generated by Django 5.1 on 2024-08-29 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_repositorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.DeleteModel(
            name='ScreenShort',
        ),
        migrations.AlterField(
            model_name='document',
            name='categoria',
            field=models.CharField(choices=[('MT', 'Manual Técnico'), ('MU', 'Manual de Usuario'), ('ET', 'Especificación Técnica'), ('DA', 'Documentación de API'), ('GI', 'Guía de Instalación'), ('IT', 'Informe Técnico'), ('DC', 'Documentación de Código')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='image',
            name='repositorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.repositorio'),
        ),
    ]
